<div class="pp-buttons-container">
    <button onclick="javascript:window.open(
        '<?= $block->escapeUrl($block->getButtonUrl()) ?>',
        'rdoauthwizard',
        'toolbar=no, location=no, directories=no, status=no, menubar=no, scrollbars=yes, resizable=yes, ,' +
        'left=100, top=100, width=1000, height=900'
        ); return false;"
            class="scalable" type="button" id="<?= /* @noEscape */ $block->getHtmlId() ?>">
        <span><span><span><?= $block->escapeHtml($block->getButtonLabel()) ?></span></span></span>
    </button>
</div>
